# Generated by Django 3.2.12 on 2023-05-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_auto_20230513_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=200)),
            ],
        ),
    ]
